### ISSUE TITLE
Json wrong format for latest version of MISP

### ISSUE THREAD

**Issue by north4g** [vmray/vmray-misp-feed#10]
When on the latest version of MISP 2.5.0, json files from VMRay is not using the correct format to upload to MISP.

**Comment by jthom-vmray** [comment]
Thanks for reporting this issue.
However, I was not able to reproduce it using MISP version 2.5.0. Importing from the VMRay feeds worked for that version for local and network feeds.
Can you describe in more detail when and where the error occurs? Or is this happening for a specific analysis/submission?

**Comment by kermana** [comment]
I can confirm the same issue on a fresh 2.5 MISP install.  Your app completes "successfully" without errors, but the resulting JSON files cannot be imported into the platform.

When I run fetchFeed:

```
2024-11-21 19:27:57 Error: [JOB ID: 24d1b19e-859f-4c92-a820-4f96a2e14de9] - failed with error code 4 after 0.093 seconds. STDERR: Error: Syntax error
#0 /mispdata/MISP/app/Lib/Tools/JsonTool.php(45): json_decode()
#1 /mispdata/MISP/app/Lib/Tools/JsonTool.php(55): JsonTool::decode()
#2 /mispdata/MISP/app/Model/Feed.php(1161): JsonTool::decodeArray()
#3 /mispdata/MISP/app/Model/Feed.php(758): Feed->__prepareFilterRules()
#4 /mispdata/MISP/app/Model/Feed.php(1275): Feed->downloadFromFeed()
#5 /mispdata/MISP/app/Console/Command/ServerShell.php(411): Feed->downloadFromFeedInitiator()
#6 /mispdata/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->fetchFeed()
#7 /mispdata/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#8 /mispdata/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#9 /mispdata/MISP/app/Console/cake.php(47): ShellDispatcher::run()
#10 {main}
. STDOUT: .

```

Currently installed version… v2.5.2 (23e6aa5f8e336c2d62d50bc59efa52257aaa279f)

**Comment by jthom-vmray** [comment]
I suspect that this issue occurs only for specific analyses. It would be very helpful if you could share either the analysis archive, the analysis ID (if you are a cloud customer), or the problematic JSON event with us.

**Comment by kermana** [comment]
Created support case #00011120 and provided samples. Please don't hesitate to talk me through the support case. Thanks!

**Comment by jthom-vmray** [comment]
I updated the documentation in regards to filter the feed. @north4g please let me know if this does not fix your issue.
