### ISSUE TITLE
Error in fetching reports from VmRay without tags

### ISSUE THREAD

**Issue by Bella-chris** [vmray/vmray-misp-feed#2]
Hello,

I have on my VmRay platform reports with and without tags and I'd like to have both as feeds on MISP. When I set the tag value in the "config.toml" file I received the below error:
<img width="545" alt="image" src="https://user-images.githubusercontent.com/92671957/190156664-934ad0f4-fab8-4a7e-ad1a-a878f9500a35.png">

Is there is a way we can set the tag value to be true without generating the above error?

**Comment by jthom-vmray** [comment]
I'm really sorry the the late response, but the error should be fixed now.
