### ISSUE TITLE
KeyError: 'filename' 

### ISSUE THREAD

**Issue by KennethNam** [vmray/vmray-misp-feed#6]
Hi !
The error occurs when calling a specific submission in MISP.
KeyError: 'filename'

Traceback (most recent call last):
  File "/opt/vmray-misp-feed/src/feed.py", line 117, in <module>
    main()
  File "/opt/vmray-misp-feed/src/feed.py", line 113, in main
    vmray_feed.update_feed()
  File "/opt/vmray-misp-feed/src/feed.py", line 87, in update_feed
    event = parser.parse(submission_id)
  File "/opt/vmray-misp-feed/src/lib/vmray/parser.py", line 1118, in parse
    for artifact in report.artifacts():
  File "/opt/vmray-misp-feed/src/lib/vmray/parser.py", line 842, in artifacts
    filename=process["filename"],
KeyError: 'filename'

[Archive.zip](https://github.com/vmray/vmray-misp-feed/files/11098057/Archive.zip)

**Comment by jthom-vmray** [comment]
Hi, thanks for reporting this issue. We will provide a fix for this.
It would be awesome if you could DM me the analysis archive, so I can retest this.

**Comment by KennethNam** [comment]
> Hi, thanks for reporting this issue. We will provide a fix for this. It would be awesome if you could DM me the analysis archive, so I can retest this.

What is an analysis archive?

**Comment by jthom-vmray** [comment]
The data this feed imports comes from analyses from a VMRay Platform Server. Each analysis can be accesses using the web interface and downloaded as an zip archive. But I recognized that it's hard to find the correct analysis that causes this issue, because we only log the submission ID, but not the analysis ID.
I will also change this.

**Comment by KennethNam** [comment]
An archive of submitted sample files?

**Comment by jthom-vmray** [comment]
To download the archive you need access to the VMRay Platform server and the submission ID from the MISP feed before the crash. The log message should look like this: `Processing submission <ID>`, directly followed by the stack trace you posted here https://github.com/vmray/vmray-misp-feed/issues/6#issue-1645250150.
Once you have the submission ID, log into the VMRay Platform console, click on submissions from the left menu. Use the advanced search to find the submission ID. Use `Submission ID` in Category, `==` as an operation and put the submission ID in the `value` field. Open the submission and click on Analyses. Each analysis has three dots on the right, hover over it and click on `Download Analysis Archive`.

The submission ID would be sufficient for me, if you are using our cloud service.

You can send us the archives via mail to <support@vmray.com>.

**Comment by KennethNam** [comment]
I understand.
We use cloud services.

Submission ID#10803374
https://cloud.vmray.com/samples/9032307

**Comment by jthom-vmray** [comment]
Thanks, we look into this.
